### ISSUE TITLE
Do poprawy

### ISSUE THREAD

**Issue by kacgrzes** [rafdy/myrepo1#1]
- [x] komentarz można usunąc. Nazwa metody dobrze sygnalizuje co robi
``` js
// metoda .read() ma za zadanie odczytać co użytkownik podał na wejściu
```
- [x] złe wcięcie  w kodzie
``` js
    switch (instruction) {
    	case '/exit':
        		process.stdout.write('Quitting app!\n');
            	process.exit(); <- tutaj
        	break;
```
- [x] usuń zakomentowany kod:
``` js		
 //   if (input !== null) {
 //       var instruction = input.toString().trim();
 //       if (instruction === '/exit') {
 //           process.stdout.write('Quitting app!\n');
 //           process.exit();
 //       } else {
 //           process.stderr.write('Wrong instruction!\n');
 //       }
 //   }
```
- [x] co jeśli zmienna `LANG === undefined`? Może powinniśmy jakoś ostrzec o tym osoby korzystające z naszego programu?

**Comment by rafdy** [comment]
Z tymi wcięciami to coś słabo mi idzie, bo w Sublime Text wcięcia są ok, a po wrzuceniu do github w podglądzie to jedno wcięcie wygląda inaczej...
