### ISSUE TITLE
Do poprawy - zadanie 1.9

### ISSUE THREAD

**Issue by kacgrzes** [rafdy/myrepo1#3]
- [x] stwórz plik `.gitignore` i dodaj do niego wpis `node_modules/` usuń katalog `node_modules/` z repozytorium
- [x] w pliku `handlers.js` brakuje obsługi błędów dla każdego zapytania
- [x] zamiast eksportować każdą funkcję osobno lepiej jest zrobić to w ten sposób:
``` js
exports = {
    upload: upload,
    welcome: welcome,
    ... // analogicznie dla pozostałych eksportowanych funkcji
}
```
- [x] aby wyświetlić 404 zamiast `console.log` możesz użyć `console.error`
- [x] popraw wcięcia w kodzie
- [x] czy wiesz czym różni się metoda `readsync`od `read` i jakie skutki niesie za sobą jej użycie?
- [ ] dałoby się zredukować `switch` w pliku `server.js` do prostszej konstrukcji. Masz jakiś pomysł jak?

**Comment by rafdy** [comment]
Co do switcha do przyznam się, że pomysłu nie mam, nie znam innej alternatywnej składni switcha. Co do readsync to z dokumentacji wynika, że to wersja synchroniczna metody, więc nie mamy callbacka, co jak domniemywam skutkowałoby tym, że jak byłby problem z odczytaniem pliku, to nie obsłużylibyśmy wyjątku i zapewne skypt by się zawiesił?

Mam serdeczną prośbę o pomoc w handlers.js. Mam zwrotkę handlers.welcome is not a function przy próbie wywołania serwera. To chyba jakiś problem przy deklaracji, ale to chyba zmęczenie materiału, nie mogę tego wyłapać...?

**Comment by rafdy** [comment]
faktycznie module.exports zamiast exports pomogło. Dzięki.
