### ISSUE TITLE
Problem z generowaniem listy

### ISSUE THREAD

**Issue by rafdy** [rafdy/myrepo1#5]
Od razu przyznaję, że zadanie nie jest kompletne, zmagam się z problemem wyświetlania listy filmów. Nie mogę poradzić sobie z tym:
Warning: Unknown props `des`, `pic` on <Movie> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in Movie
    in ul
    in div

**Comment by kacgrzes** [comment]
Czy ten błąd jest dalej aktualny?
